# Generated by Django 5.1.7 on 2025-03-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=9)),
                ('activity', models.CharField(max_length=30)),
                ('term', models.IntegerField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('days', models.CharField(max_length=50)),
            ],
        ),
    ]
